//////////////////////////////////////////////////////////////////////
/// \file  dg_version.h
/// \brief DG software version
///
/// Copyright 2021 DeGirum Corporation
///
/// This file defines DG software version information including
/// major and minor versions, and git branch and revision information
///
/// Generated by cmake from dg_version.h.in file. DO NOT EDIT!
///


#ifndef DG_GLOBAL_VERSION_H
#define DG_GLOBAL_VERSION_H

#ifndef DG_VERSION_MAJOR
	#define DG_VERSION_MAJOR 0
#endif
#ifndef DG_VERSION_MINOR
	#define DG_VERSION_MINOR 9
#endif
#ifndef DG_VERSION_REVISION
	#define DG_VERSION_REVISION 5
#endif
#ifndef DG_GIT_REV
	#define DG_GIT_REV 	"5c0a62a"
#endif
#ifndef DG_GIT_TAG
	#define DG_GIT_TAG 	""
#endif
#ifndef DG_GIT_BRANCH
	#define DG_GIT_BRANCH 	"0.9.5"
#endif

#endif // DG_GLOBAL_VERSION_H
